name: Shell Commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntua-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multipline script
        run: |
           node -v
           npm -v